language: node_js
cache: yarn
matrix:
  include:
  - node_js: '8'
    env: RUN_SNYK=true
  - node_js: '10'
  - node_js: node
script:
- yarn lint
- yarn test --coverage
- yarn prettier:ci
- yarn build
before_install:
- if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi
install:
- if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi
- yarn install
after_success:
- if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $RUN_SNYK
  && $SNYK_TOKEN ]]; then snyk monitor --org=maxmind --project-name=maxmind/GeoIP2-node;
  fi
env:
  global:
  - secure: ks7L7XChEsmVTE3l9cwU6yufoO/7ENaRu09oTO76l64lwgD6v2BgqEParj3w/QXMjoETvHJA4/biiP4WOp3PmMc0bhtcwI9vFDHaKr8PuWLV7QtuFGgZp8RGakeY8eNQMDMvcxdLMOlKrhTmdpT5PfDC7hFMTdiXphpMni+C1poUcqmoElq++aEO3eMFl50Yc7ACS2Im53C3yY8UJ3zp51UDqCx9P6uU96m6RMvq0Eg796BG3rVJaBlrNI4HGBOpqXfQUx0SC2IQ/aHAHvmHp+tvEvPD6DGFM7/vRIREdMLN99eK+M8ooMSKD/6XYU9LuPO9+9Umj/1GtjgZVH/RSge98RoK86apYTHUJwTq5ZGZ9yw8UTBDXh/s7Rn5hduL0PnE3/+nCG/BFPLG2iPeSOEKA9HyAsRFdXs2IJuI9KG70LgN4H0SfML5em1OM/fCD10jF9I+vsscKKa1Kv7stiHaHYSkp+JskAmKx0T6DocvOJYJ+8nMA1DU6P9nChCxtTNaQ8vS/vRbyIkyj3/J3udjjZZwns76AHkqZE2SayhW+08rqJdhyCum/J5Ngb2QdwAwIr4nXK1meBLKYcYz+b6S8ox0zwSuGWRS1sSoO24F2zT4CT7Wg6GK4yJkVfzv0yMroOC48UipzAk1ckxtLPXvSOU3ZJWuQzcbyIXQHak=
