---
language: node_js
cache: yarn
matrix:
  include:
    - node_js: '8'
    - node_js: '10'
      env: RUN_SNYK=true
    - node_js: node
script:
  - yarn lint
  - yarn test --coverage
  - yarn prettier:ci
  - yarn build
  - yarn link
  - cd e2e/js
  - yarn
  - yarn link '@maxmind/geoip2-node'
  - yarn jest
  - cd ../ts
  - yarn
  - yarn link '@maxmind/geoip2-node'
  - yarn jest
before_install:
  - npm install -g yarn
  - if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi
install:
  - if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi
  - yarn install
after_success:
  - if [[ $TRAVIS_BRANCH == 'master'
         && $TRAVIS_PULL_REQUEST == 'false'
         && $RUN_SNYK
         && $SNYK_TOKEN
    ]]; then
      snyk monitor --org=maxmind --project-name=maxmind/GeoIP2-node;
    fi
env:
  global:
  - secure: uFkgqd28i3Zan7h/vKcg7vEgzIo34iBGaUUpdWHGjSfvFngo4Q2PRC1eJzgR9I3qG1n4DpiwUidrVC0wp3aOinkn5eDe78OVUlCLFmdoTDSMFZx101F1+GuMA0J5IDgHvgZGkp4wZqOUAc8qL5t4D/KHE+x79vg1RHm72Z7OalzGtQlbKeSeKYNoGxaAALrv4Z9MYanROhDFiEjtjajRSVLFPH7f2Bn5fmEOFxx84iEe5LFnP82EFAZgmTDgzefFMIEX7TYidDySIe1L6ubcTvI8WRK6+zV49cWY0zvEBivySha+dHH7W3zCleIQCPD7ybcKPySPuW5/X3QPfjoXHG1UhShWhovCzkbXP7tAfdHEedbKDrlzMXeM34rICcBqfMJa4onsS7MNvo9B+OnVRCCJ58/WVuATvSLH0VgdVSSj8C/A/41hGdZVsRQVjyiu3YIS20xjrkYdBHzclePc7cdNCDIj9EgcRpL+9OlEKs1BKx9AK+4tf0brcHMEFXUM52lUB3Ltgh4DnmQF2pOu7oJmOagH3jPHOz7u8QG6Pets4mgA4wIas9JltCedNgDzmiZYlMSgcxkQIiizxXjClkrB6mRJ3uE0oMXPslOaHeolT1p16ZFa/2pBmwPHQ583Ys+87W1hxkUdnaSCDs40WtdVmFhU5iUI11j1IP8dfes=
