language: node_js
cache: yarn
matrix:
  include:
  - node_js: '8'
    env: RUN_SNYK=true
  - node_js: '10'
  - node_js: node
script:
- yarn lint
- yarn test --coverage
- yarn prettier:ci
- yarn build
before_install:
- if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi
install:
- if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi
- yarn install
after_success:
- if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $RUN_SNYK
  && $SNYK_TOKEN ]]; then snyk monitor --org=maxmind --project-name=maxmind/GeoIP2-node;
  fi
env:
  global:
  - secure: nEzxlVF5ZvD3z7o2XbtzKN/WwnU4bGLmImIi7xbPL36qHTpdWWr2UMbOIOjWc1BHjMY3TaJAmVOrtNgM7g6dkvhNFWfVjD1iKTeKxhzYWj2ZkTKhy7bNuSiXJNSsGirAw2gonV4LDq4pjrMNZG0SLhOxnI4wEibYr3RS+Jb3JeIoDFDuVWqwVu/r3TQYx6bvz5xi2xqsyi9UJ0PB0HScoici4xRK9S8OBGjQDaJ4yNsI0vGzWl5lhbtvj2wRlZzAj0PJTsV2VuYUhCTqSXIkr4MBuLKSp93rJrq68RAktW4amhj3HBNXURU5+8gU2FdiQYVlhn01MqZLmJhlZO1AX0FEmbTkJ7jJdtw0v7qNvGwxz2MyMKxQKFZ2EeTqN/26o+vHvRR0YSfAMJqtVTSKCtjs0Z0nFHq7Nv0Oi9vnfgP2itVb1SzZakvxF/05V0wDvHUCwKcBnuig5FuVJ7hnSgtKj2dCgOmIBO5eMwTzk70Vg2EPsm5KJCNeG8rwzq3PxzylXiyk0a8BK5PvTuM0keTA1FNLen2+Aq6EKP1rayMoGSUo815fhItNJdUv+xRmFk5rMAfoxsiXL+sDIF+rq9WrjUarqF2Ge+l4xMYNo8iGnQk52bxy6jCXhP+zLhSUdXC367V0u4lZPuqUzMezZotInt4wj5TjqUbaCXVayQ8=
